### ISSUE TITLE
Error importing SimpleSerializer

### ISSUE THREAD

**Issue by zishanahmed08** [devpi/devpi-lockdown#1]
I get import error as below
```
from pyramid.authentication import _SimpleSerializer
ImportError: cannot import name '_SimpleSerializer'
```

However I notice that the `authentication.py` itself imports `from pyramid.util import SimpleSerializer`
Where am I going wrong?

**Comment by fschulze** [comment]
Can you try the patch in #2?

**Comment by zishanahmed08** [comment]
I checked the patch and it works.Thanks a lot @fschulze

**Comment by zishanahmed08** [comment]
@fschulze When do you intend to release the updated version officially?

**Comment by zishanahmed08** [comment]
@fschulze A gentle reminder
