### ISSUE TITLE
Search box retuning an error.

### ISSUE THREAD

**Issue by neverased** [devpi/devpi-lockdown#7]
While enabling devpi-lockdown, and trying to search, initially search box returns:

![Screenshot 2023-05-24 at 12 44 07](https://github.com/devpi/devpi-lockdown/assets/37114938/7485203c-56a4-44a9-a7d7-dc5e5af98158)

After clicking search tho, everything is working perfectly fine.

During typing inside the search box, web console returns:

![Screenshot 2023-05-24 at 12 46 19](https://github.com/devpi/devpi-lockdown/assets/37114938/599b293a-9bbd-47e1-b5f9-5b9964e2b258)

Looking at the server while typing, it always shows:

<img width="257" alt="Screenshot 2023-05-24 at 12 47 48" src="https://github.com/devpi/devpi-lockdown/assets/37114938/bc0ea81d-f081-4eb5-af80-66842934ff9f">

I wonder if it is a known issue or a configuration problem.

**Comment by fschulze** [comment]
Do you have a theme installed? The default devpi-web theme doesn't do queries while typing and your partial screenshot looks unfamiliar to me. The theme might need to be adapted to work with devpi-lockdown.

**Comment by neverased** [comment]
Yes, I am using a theme :) In that case, I will try to adapt it to support the search.

Thank you!

**Comment by fschulze** [comment]
Feel free to ask questions if you are stuck.
